.ALIASES
R_R1            R1(1=IN 2=OUT ) CN @RESISTORS.SCHEMATIC1(sch_1):INS443@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=OUT ) CN @RESISTORS.SCHEMATIC1(sch_1):INS459@ANALOG.R.Normal(chips)
V_V1            V1(+=IN -=0 ) CN @RESISTORS.SCHEMATIC1(sch_1):INS546@SOURCE.VDC.Normal(chips)
C_C1            C1(1=0 2=OUT ) CN @RESISTORS.SCHEMATIC1(sch_1):INS655@ANALOG.C.Normal(chips)
_    _(in=IN)
_    _(out=OUT)
.ENDALIASES
